// Generated by CoffeeScript 1.7.0
(function() {
  var Modal, ModalDialog,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Modal = require('voxel-modal');

  ModalDialog = (function(_super) {
    __extends(ModalDialog, _super);

    function ModalDialog(game, opts) {
      var content, _i, _len, _ref;
      this.game = game;
      if (opts == null) {
        opts = {};
      }
      if (opts.contents == null) {
        opts.contents = [];
      }
      if (typeof document !== "undefined" && document !== null) {
        this.aligner = document.createElement('div');
        this.aligner.setAttribute('class', 'voxel-modal-dialog-aligner');
        this.aligner.setAttribute('style', 'display: flex; align-items: center; justify-content: center; top: 0px; left: 0px; width: 100%; height: 90%; position: fixed; pointer-events: none;');
        this.box = document.createElement('div');
        this.box.setAttribute('class', 'voxel-modal-dialog');
        this.box.style.border = '6px outset gray';
        this.box.style.visibility = 'hidden';
        this.box.style.zIndex = 1;
        this.box.style.pointerEvents = 'auto';
        this.box.style.backgroundImage = 'linear-gradient(rgba(255,255,255,0.5) 0%, rgba(255,255,255,0.5) 100%)';
        _ref = opts.contents;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          content = _ref[_i];
          this.box.appendChild(content);
        }
        this.aligner.appendChild(this.box);
        document.body.appendChild(this.aligner);
      }
      opts.element = this.box;
      ModalDialog.__super__.constructor.call(this, game, opts);
    }

    return ModalDialog;

  })(Modal);

  module.exports = ModalDialog;

}).call(this);
